version: "3.3"

services:
  tradingDiariesDB:
    image: postgres:latest
    environment:
      POSTGRES_DB: tradingDiaries
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asz150Ra
    ports:
      - "5432:5432"
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=rodrx20@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - 5050:80
