version: "3.3"

services:
  trading-diaries:
    image: postgres:latest
    environment:
      POSTGRES_DB: trading-diaries
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - "/postgres_data:/var/lib/postgresql/trading-diaries"

  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=rodrx20@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - 5050:80
